"""AUTOMATISCH ERZEUGT aus app/gui/package/package_form.ui - nicht von Hand aendern.

Geaendert wird die .ui-Datei im Qt Designer, danach:

    python tools/build_ui.py
"""

#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PackageForm(object):
    def setupUi(self, PackageForm):
        PackageForm.setObjectName("PackageForm")
        self.root = QtWidgets.QHBoxLayout(PackageForm)
        self.root.setContentsMargins(0, 0, 0, 0)
        self.root.setSpacing(12)
        self.root.setObjectName("root")
        self.input_box = QtWidgets.QGroupBox(parent=PackageForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_box.sizePolicy().hasHeightForWidth())
        self.input_box.setSizePolicy(sizePolicy)
        self.input_box.setObjectName("input_box")
        self.input_grid = QtWidgets.QGridLayout(self.input_box)
        self.input_grid.setContentsMargins(12, 16, 12, 8)
        self.input_grid.setHorizontalSpacing(8)
        self.input_grid.setVerticalSpacing(2)
        self.input_grid.setObjectName("input_grid")
        self.length_label = QtWidgets.QLabel(parent=self.input_box)
        self.length_label.setMinimumSize(QtCore.QSize(0, 26))
        self.length_label.setObjectName("length_label")
        self.input_grid.addWidget(self.length_label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.length = NumberField(parent=self.input_box)
        self.length.setObjectName("length")
        self.input_grid.addWidget(self.length, 0, 1, 1, 1)
        self.width_label = QtWidgets.QLabel(parent=self.input_box)
        self.width_label.setMinimumSize(QtCore.QSize(0, 26))
        self.width_label.setObjectName("width_label")
        self.input_grid.addWidget(self.width_label, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.width = NumberField(parent=self.input_box)
        self.width.setObjectName("width")
        self.input_grid.addWidget(self.width, 0, 3, 1, 1)
        self.height_label = QtWidgets.QLabel(parent=self.input_box)
        self.height_label.setMinimumSize(QtCore.QSize(0, 26))
        self.height_label.setObjectName("height_label")
        self.input_grid.addWidget(self.height_label, 0, 4, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.height = NumberField(parent=self.input_box)
        self.height.setObjectName("height")
        self.input_grid.addWidget(self.height, 0, 5, 1, 1)
        self.weight_label = QtWidgets.QLabel(parent=self.input_box)
        self.weight_label.setMinimumSize(QtCore.QSize(0, 26))
        self.weight_label.setObjectName("weight_label")
        self.input_grid.addWidget(self.weight_label, 0, 6, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.weight = NumberField(parent=self.input_box)
        self.weight.setObjectName("weight")
        self.input_grid.addWidget(self.weight, 0, 7, 1, 1)
        self.stack_load_label = QtWidgets.QLabel(parent=self.input_box)
        self.stack_load_label.setMinimumSize(QtCore.QSize(0, 26))
        self.stack_load_label.setObjectName("stack_load_label")
        self.input_grid.addWidget(self.stack_load_label, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.stack_load = NumberField(parent=self.input_box)
        self.stack_load.setObjectName("stack_load")
        self.input_grid.addWidget(self.stack_load, 1, 1, 1, 3)
        self.label_caption = QtWidgets.QLabel(parent=self.input_box)
        self.label_caption.setMinimumSize(QtCore.QSize(0, 26))
        self.label_caption.setObjectName("label_caption")
        self.input_grid.addWidget(self.label_caption, 1, 4, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_field = QtWidgets.QLineEdit(parent=self.input_box)
        self.label_field.setMinimumSize(QtCore.QSize(0, 26))
        self.label_field.setObjectName("label_field")
        self.input_grid.addWidget(self.label_field, 1, 5, 1, 2, QtCore.Qt.AlignmentFlag.AlignTop)
        self.tipping = QtWidgets.QCheckBox(parent=self.input_box)
        self.tipping.setMinimumSize(QtCore.QSize(0, 26))
        self.tipping.setObjectName("tipping")
        self.input_grid.addWidget(self.tipping, 1, 7, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.root.addWidget(self.input_box)
        self.derived = ResultGrid(parent=PackageForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.derived.sizePolicy().hasHeightForWidth())
        self.derived.setSizePolicy(sizePolicy)
        self.derived.setObjectName("derived")
        self.root.addWidget(self.derived)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.root.addItem(spacerItem)

        self.retranslateUi(PackageForm)
        QtCore.QMetaObject.connectSlotsByName(PackageForm)

    def retranslateUi(self, PackageForm):
        _translate = QtCore.QCoreApplication.translate
        PackageForm.setWindowTitle(_translate("PackageForm", "Paketdaten"))
        self.input_box.setTitle(_translate("PackageForm", "Paketdaten"))
        self.length_label.setText(_translate("PackageForm", "Laenge"))
        self.width_label.setText(_translate("PackageForm", "Breite"))
        self.height_label.setText(_translate("PackageForm", "Hoehe"))
        self.weight_label.setText(_translate("PackageForm", "Gewicht"))
        self.stack_load_label.setText(_translate("PackageForm", "Max. Stapellast"))
        self.label_caption.setText(_translate("PackageForm", "Bezeichnung"))
        self.label_field.setPlaceholderText(_translate("PackageForm", "Optional: Artikelnummer"))
        self.tipping.setText(_translate("PackageForm", "Kippen erlaubt"))
        self.tipping.setToolTip(_translate("PackageForm", "Aus: das Paket wird nur in der Ebene um 90 Grad gedreht (\'oben bleibt oben\').\n"
"Ein: der Optimierer darf auch Laenge oder Breite hochkant stellen."))
        self.derived.setTitle(_translate("PackageForm", "Abgeleitete Werte"))
from app.gui.common.widgets import NumberField, ResultGrid
